name: TypeScript

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run tsc

  tsgo:
    name: tsgo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run tsgo